/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BrokerRouteImport } from './routes/broker'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResetPasswordIndexRouteImport } from './routes/reset-password.index'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as BrokerIndexRouteImport } from './routes/broker.index'
import { Route as AgentIndexRouteImport } from './routes/agent.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ResetPasswordConfirmRouteImport } from './routes/reset-password.confirm'
import { Route as ReserveIdRouteImport } from './routes/reserve.$id'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as OnboardingPropertyRouteImport } from './routes/onboarding.property'
import { Route as OnboardingMediaRouteImport } from './routes/onboarding.media'
import { Route as OnboardingListingRouteImport } from './routes/onboarding.listing'
import { Route as OnboardingIdentityRouteImport } from './routes/onboarding.identity'
import { Route as OnboardingFeeRouteImport } from './routes/onboarding.fee'
import { Route as OnboardingAgreementRouteImport } from './routes/onboarding.agreement'
import { Route as ListingsNewRouteImport } from './routes/listings.new'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'
import { Route as DataRoomIdRouteImport } from './routes/data-room.$id'
import { Route as BuyerWishlistRouteImport } from './routes/buyer.wishlist'
import { Route as BuyerVerificationRouteImport } from './routes/buyer.verification'
import { Route as BuyerRegisterRouteImport } from './routes/buyer.register'
import { Route as BuyerLoginRouteImport } from './routes/buyer.login'
import { Route as BuyerGoldenTicketRouteImport } from './routes/buyer.golden-ticket'
import { Route as BuyerDocumentsRouteImport } from './routes/buyer.documents'
import { Route as BuyerDashboardRouteImport } from './routes/buyer.dashboard'
import { Route as BuyerAdverseActionRouteImport } from './routes/buyer.adverse-action'
import { Route as BrokerRegisterRouteImport } from './routes/broker.register'
import { Route as BrokerLoginRouteImport } from './routes/broker.login'
import { Route as BrokerDashboardRouteImport } from './routes/broker.dashboard'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AgentRegisterRouteImport } from './routes/agent.register'
import { Route as AgentLoginRouteImport } from './routes/agent.login'
import { Route as AgentDashboardRouteImport } from './routes/agent.dashboard'
import { Route as AgentBrokerRelationshipRouteImport } from './routes/agent.broker-relationship'
import { Route as AdminSubstitutionsRouteImport } from './routes/admin.substitutions'
import { Route as AdminSellersRouteImport } from './routes/admin.sellers'
import { Route as AdminPropertiesRouteImport } from './routes/admin.properties'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminContactsRouteImport } from './routes/admin.contacts'
import { Route as AdminBuyersRouteImport } from './routes/admin.buyers'
import { Route as AdminBrokersRouteImport } from './routes/admin.brokers'
import { Route as AdminAuditLogRouteImport } from './routes/admin.audit-log'
import { Route as BuyerOnboardingIndexRouteImport } from './routes/buyer.onboarding.index'
import { Route as BuyerOnboardingVettingRouteImport } from './routes/buyer.onboarding.vetting'
import { Route as BuyerOnboardingPaymentRouteImport } from './routes/buyer.onboarding.payment'
import { Route as BuyerOnboardingLiquidityRouteImport } from './routes/buyer.onboarding.liquidity'
import { Route as BuyerOnboardingLifestyleRouteImport } from './routes/buyer.onboarding.lifestyle'
import { Route as BuyerOnboardingIdentityRouteImport } from './routes/buyer.onboarding.identity'
import { Route as BrokerOnboardingLicenseCheckRouteImport } from './routes/broker.onboarding.license-check'
import { Route as BrokerOnboardingInsuranceRouteImport } from './routes/broker.onboarding.insurance'
import { Route as BrokerOnboardingComplianceRouteImport } from './routes/broker.onboarding.compliance'
import { Route as BrokerOnboardingBankingRouteImport } from './routes/broker.onboarding.banking'
import { Route as ApiPublicNarCertSweepRouteImport } from './routes/api.public.nar-cert-sweep'
import { Route as ApiPublicEnrollmentMaintenanceRouteImport } from './routes/api.public.enrollment-maintenance'
import { Route as ApiPublicBrokerRelationshipSweepRouteImport } from './routes/api.public.broker-relationship-sweep'
import { Route as ApiPublicArelloRetryRouteImport } from './routes/api.public.arello-retry'
import { Route as AgentOnboardingLicenseDetailsRouteImport } from './routes/agent.onboarding.license-details'
import { Route as AgentOnboardingLicenseCheckRouteImport } from './routes/agent.onboarding.license-check'
import { Route as AgentOnboardingInsuranceRouteImport } from './routes/agent.onboarding.insurance'
import { Route as AgentOnboardingComplianceRouteImport } from './routes/agent.onboarding.compliance'
import { Route as AgentOnboardingBrokerRouteImport } from './routes/agent.onboarding.broker'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokerRoute = BrokerRouteImport.update({
  id: '/broker',
  path: '/broker',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordIndexRoute = ResetPasswordIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResetPasswordRoute,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/properties/',
  path: '/properties/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokerIndexRoute = BrokerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrokerRoute,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AgentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ResetPasswordConfirmRoute = ResetPasswordConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => ResetPasswordRoute,
} as any)
const ReserveIdRoute = ReserveIdRouteImport.update({
  id: '/reserve/$id',
  path: '/reserve/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/properties/$id',
  path: '/properties/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingPropertyRoute = OnboardingPropertyRouteImport.update({
  id: '/onboarding/property',
  path: '/onboarding/property',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingMediaRoute = OnboardingMediaRouteImport.update({
  id: '/onboarding/media',
  path: '/onboarding/media',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingListingRoute = OnboardingListingRouteImport.update({
  id: '/onboarding/listing',
  path: '/onboarding/listing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIdentityRoute = OnboardingIdentityRouteImport.update({
  id: '/onboarding/identity',
  path: '/onboarding/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingFeeRoute = OnboardingFeeRouteImport.update({
  id: '/onboarding/fee',
  path: '/onboarding/fee',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingAgreementRoute = OnboardingAgreementRouteImport.update({
  id: '/onboarding/agreement',
  path: '/onboarding/agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsNewRoute = ListingsNewRouteImport.update({
  id: '/listings/new',
  path: '/listings/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoomIdRoute = DataRoomIdRouteImport.update({
  id: '/data-room/$id',
  path: '/data-room/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerWishlistRoute = BuyerWishlistRouteImport.update({
  id: '/buyer/wishlist',
  path: '/buyer/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerVerificationRoute = BuyerVerificationRouteImport.update({
  id: '/buyer/verification',
  path: '/buyer/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerRegisterRoute = BuyerRegisterRouteImport.update({
  id: '/buyer/register',
  path: '/buyer/register',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerLoginRoute = BuyerLoginRouteImport.update({
  id: '/buyer/login',
  path: '/buyer/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerGoldenTicketRoute = BuyerGoldenTicketRouteImport.update({
  id: '/buyer/golden-ticket',
  path: '/buyer/golden-ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerDocumentsRoute = BuyerDocumentsRouteImport.update({
  id: '/buyer/documents',
  path: '/buyer/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerDashboardRoute = BuyerDashboardRouteImport.update({
  id: '/buyer/dashboard',
  path: '/buyer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerAdverseActionRoute = BuyerAdverseActionRouteImport.update({
  id: '/buyer/adverse-action',
  path: '/buyer/adverse-action',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokerRegisterRoute = BrokerRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => BrokerRoute,
} as any)
const BrokerLoginRoute = BrokerLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => BrokerRoute,
} as any)
const BrokerDashboardRoute = BrokerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => BrokerRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRegisterRoute = AgentRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AgentRoute,
} as any)
const AgentLoginRoute = AgentLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AgentRoute,
} as any)
const AgentDashboardRoute = AgentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AgentRoute,
} as any)
const AgentBrokerRelationshipRoute = AgentBrokerRelationshipRouteImport.update({
  id: '/broker-relationship',
  path: '/broker-relationship',
  getParentRoute: () => AgentRoute,
} as any)
const AdminSubstitutionsRoute = AdminSubstitutionsRouteImport.update({
  id: '/substitutions',
  path: '/substitutions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSellersRoute = AdminSellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPropertiesRoute = AdminPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBuyersRoute = AdminBuyersRouteImport.update({
  id: '/buyers',
  path: '/buyers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBrokersRoute = AdminBrokersRouteImport.update({
  id: '/brokers',
  path: '/brokers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRoute,
} as any)
const BuyerOnboardingIndexRoute = BuyerOnboardingIndexRouteImport.update({
  id: '/buyer/onboarding/',
  path: '/buyer/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerOnboardingVettingRoute = BuyerOnboardingVettingRouteImport.update({
  id: '/buyer/onboarding/vetting',
  path: '/buyer/onboarding/vetting',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerOnboardingPaymentRoute = BuyerOnboardingPaymentRouteImport.update({
  id: '/buyer/onboarding/payment',
  path: '/buyer/onboarding/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerOnboardingLiquidityRoute =
  BuyerOnboardingLiquidityRouteImport.update({
    id: '/buyer/onboarding/liquidity',
    path: '/buyer/onboarding/liquidity',
    getParentRoute: () => rootRouteImport,
  } as any)
const BuyerOnboardingLifestyleRoute =
  BuyerOnboardingLifestyleRouteImport.update({
    id: '/buyer/onboarding/lifestyle',
    path: '/buyer/onboarding/lifestyle',
    getParentRoute: () => rootRouteImport,
  } as any)
const BuyerOnboardingIdentityRoute = BuyerOnboardingIdentityRouteImport.update({
  id: '/buyer/onboarding/identity',
  path: '/buyer/onboarding/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const BrokerOnboardingLicenseCheckRoute =
  BrokerOnboardingLicenseCheckRouteImport.update({
    id: '/onboarding/license-check',
    path: '/onboarding/license-check',
    getParentRoute: () => BrokerRoute,
  } as any)
const BrokerOnboardingInsuranceRoute =
  BrokerOnboardingInsuranceRouteImport.update({
    id: '/onboarding/insurance',
    path: '/onboarding/insurance',
    getParentRoute: () => BrokerRoute,
  } as any)
const BrokerOnboardingComplianceRoute =
  BrokerOnboardingComplianceRouteImport.update({
    id: '/onboarding/compliance',
    path: '/onboarding/compliance',
    getParentRoute: () => BrokerRoute,
  } as any)
const BrokerOnboardingBankingRoute = BrokerOnboardingBankingRouteImport.update({
  id: '/onboarding/banking',
  path: '/onboarding/banking',
  getParentRoute: () => BrokerRoute,
} as any)
const ApiPublicNarCertSweepRoute = ApiPublicNarCertSweepRouteImport.update({
  id: '/api/public/nar-cert-sweep',
  path: '/api/public/nar-cert-sweep',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEnrollmentMaintenanceRoute =
  ApiPublicEnrollmentMaintenanceRouteImport.update({
    id: '/api/public/enrollment-maintenance',
    path: '/api/public/enrollment-maintenance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBrokerRelationshipSweepRoute =
  ApiPublicBrokerRelationshipSweepRouteImport.update({
    id: '/api/public/broker-relationship-sweep',
    path: '/api/public/broker-relationship-sweep',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicArelloRetryRoute = ApiPublicArelloRetryRouteImport.update({
  id: '/api/public/arello-retry',
  path: '/api/public/arello-retry',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentOnboardingLicenseDetailsRoute =
  AgentOnboardingLicenseDetailsRouteImport.update({
    id: '/onboarding/license-details',
    path: '/onboarding/license-details',
    getParentRoute: () => AgentRoute,
  } as any)
const AgentOnboardingLicenseCheckRoute =
  AgentOnboardingLicenseCheckRouteImport.update({
    id: '/onboarding/license-check',
    path: '/onboarding/license-check',
    getParentRoute: () => AgentRoute,
  } as any)
const AgentOnboardingInsuranceRoute =
  AgentOnboardingInsuranceRouteImport.update({
    id: '/onboarding/insurance',
    path: '/onboarding/insurance',
    getParentRoute: () => AgentRoute,
  } as any)
const AgentOnboardingComplianceRoute =
  AgentOnboardingComplianceRouteImport.update({
    id: '/onboarding/compliance',
    path: '/onboarding/compliance',
    getParentRoute: () => AgentRoute,
  } as any)
const AgentOnboardingBrokerRoute = AgentOnboardingBrokerRouteImport.update({
  id: '/onboarding/broker',
  path: '/onboarding/broker',
  getParentRoute: () => AgentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/broker': typeof BrokerRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRouteWithChildren
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/brokers': typeof AdminBrokersRoute
  '/admin/buyers': typeof AdminBuyersRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/substitutions': typeof AdminSubstitutionsRoute
  '/agent/broker-relationship': typeof AgentBrokerRelationshipRoute
  '/agent/dashboard': typeof AgentDashboardRoute
  '/agent/login': typeof AgentLoginRoute
  '/agent/register': typeof AgentRegisterRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/broker/dashboard': typeof BrokerDashboardRoute
  '/broker/login': typeof BrokerLoginRoute
  '/broker/register': typeof BrokerRegisterRoute
  '/buyer/adverse-action': typeof BuyerAdverseActionRoute
  '/buyer/dashboard': typeof BuyerDashboardRoute
  '/buyer/documents': typeof BuyerDocumentsRoute
  '/buyer/golden-ticket': typeof BuyerGoldenTicketRoute
  '/buyer/login': typeof BuyerLoginRoute
  '/buyer/register': typeof BuyerRegisterRoute
  '/buyer/verification': typeof BuyerVerificationRoute
  '/buyer/wishlist': typeof BuyerWishlistRoute
  '/data-room/$id': typeof DataRoomIdRoute
  '/listings/$id': typeof ListingsIdRoute
  '/listings/new': typeof ListingsNewRoute
  '/onboarding/agreement': typeof OnboardingAgreementRoute
  '/onboarding/fee': typeof OnboardingFeeRoute
  '/onboarding/identity': typeof OnboardingIdentityRoute
  '/onboarding/listing': typeof OnboardingListingRoute
  '/onboarding/media': typeof OnboardingMediaRoute
  '/onboarding/property': typeof OnboardingPropertyRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/r/$token': typeof RTokenRoute
  '/reserve/$id': typeof ReserveIdRoute
  '/reset-password/confirm': typeof ResetPasswordConfirmRoute
  '/admin/': typeof AdminIndexRoute
  '/agent/': typeof AgentIndexRoute
  '/broker/': typeof BrokerIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/agent/onboarding/broker': typeof AgentOnboardingBrokerRoute
  '/agent/onboarding/compliance': typeof AgentOnboardingComplianceRoute
  '/agent/onboarding/insurance': typeof AgentOnboardingInsuranceRoute
  '/agent/onboarding/license-check': typeof AgentOnboardingLicenseCheckRoute
  '/agent/onboarding/license-details': typeof AgentOnboardingLicenseDetailsRoute
  '/api/public/arello-retry': typeof ApiPublicArelloRetryRoute
  '/api/public/broker-relationship-sweep': typeof ApiPublicBrokerRelationshipSweepRoute
  '/api/public/enrollment-maintenance': typeof ApiPublicEnrollmentMaintenanceRoute
  '/api/public/nar-cert-sweep': typeof ApiPublicNarCertSweepRoute
  '/broker/onboarding/banking': typeof BrokerOnboardingBankingRoute
  '/broker/onboarding/compliance': typeof BrokerOnboardingComplianceRoute
  '/broker/onboarding/insurance': typeof BrokerOnboardingInsuranceRoute
  '/broker/onboarding/license-check': typeof BrokerOnboardingLicenseCheckRoute
  '/buyer/onboarding/identity': typeof BuyerOnboardingIdentityRoute
  '/buyer/onboarding/lifestyle': typeof BuyerOnboardingLifestyleRoute
  '/buyer/onboarding/liquidity': typeof BuyerOnboardingLiquidityRoute
  '/buyer/onboarding/payment': typeof BuyerOnboardingPaymentRoute
  '/buyer/onboarding/vetting': typeof BuyerOnboardingVettingRoute
  '/buyer/onboarding/': typeof BuyerOnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/brokers': typeof AdminBrokersRoute
  '/admin/buyers': typeof AdminBuyersRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/substitutions': typeof AdminSubstitutionsRoute
  '/agent/broker-relationship': typeof AgentBrokerRelationshipRoute
  '/agent/dashboard': typeof AgentDashboardRoute
  '/agent/login': typeof AgentLoginRoute
  '/agent/register': typeof AgentRegisterRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/broker/dashboard': typeof BrokerDashboardRoute
  '/broker/login': typeof BrokerLoginRoute
  '/broker/register': typeof BrokerRegisterRoute
  '/buyer/adverse-action': typeof BuyerAdverseActionRoute
  '/buyer/dashboard': typeof BuyerDashboardRoute
  '/buyer/documents': typeof BuyerDocumentsRoute
  '/buyer/golden-ticket': typeof BuyerGoldenTicketRoute
  '/buyer/login': typeof BuyerLoginRoute
  '/buyer/register': typeof BuyerRegisterRoute
  '/buyer/verification': typeof BuyerVerificationRoute
  '/buyer/wishlist': typeof BuyerWishlistRoute
  '/data-room/$id': typeof DataRoomIdRoute
  '/listings/$id': typeof ListingsIdRoute
  '/listings/new': typeof ListingsNewRoute
  '/onboarding/agreement': typeof OnboardingAgreementRoute
  '/onboarding/fee': typeof OnboardingFeeRoute
  '/onboarding/identity': typeof OnboardingIdentityRoute
  '/onboarding/listing': typeof OnboardingListingRoute
  '/onboarding/media': typeof OnboardingMediaRoute
  '/onboarding/property': typeof OnboardingPropertyRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/r/$token': typeof RTokenRoute
  '/reserve/$id': typeof ReserveIdRoute
  '/reset-password/confirm': typeof ResetPasswordConfirmRoute
  '/admin': typeof AdminIndexRoute
  '/agent': typeof AgentIndexRoute
  '/broker': typeof BrokerIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/properties': typeof PropertiesIndexRoute
  '/reset-password': typeof ResetPasswordIndexRoute
  '/agent/onboarding/broker': typeof AgentOnboardingBrokerRoute
  '/agent/onboarding/compliance': typeof AgentOnboardingComplianceRoute
  '/agent/onboarding/insurance': typeof AgentOnboardingInsuranceRoute
  '/agent/onboarding/license-check': typeof AgentOnboardingLicenseCheckRoute
  '/agent/onboarding/license-details': typeof AgentOnboardingLicenseDetailsRoute
  '/api/public/arello-retry': typeof ApiPublicArelloRetryRoute
  '/api/public/broker-relationship-sweep': typeof ApiPublicBrokerRelationshipSweepRoute
  '/api/public/enrollment-maintenance': typeof ApiPublicEnrollmentMaintenanceRoute
  '/api/public/nar-cert-sweep': typeof ApiPublicNarCertSweepRoute
  '/broker/onboarding/banking': typeof BrokerOnboardingBankingRoute
  '/broker/onboarding/compliance': typeof BrokerOnboardingComplianceRoute
  '/broker/onboarding/insurance': typeof BrokerOnboardingInsuranceRoute
  '/broker/onboarding/license-check': typeof BrokerOnboardingLicenseCheckRoute
  '/buyer/onboarding/identity': typeof BuyerOnboardingIdentityRoute
  '/buyer/onboarding/lifestyle': typeof BuyerOnboardingLifestyleRoute
  '/buyer/onboarding/liquidity': typeof BuyerOnboardingLiquidityRoute
  '/buyer/onboarding/payment': typeof BuyerOnboardingPaymentRoute
  '/buyer/onboarding/vetting': typeof BuyerOnboardingVettingRoute
  '/buyer/onboarding': typeof BuyerOnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/agent': typeof AgentRouteWithChildren
  '/broker': typeof BrokerRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRouteWithChildren
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/brokers': typeof AdminBrokersRoute
  '/admin/buyers': typeof AdminBuyersRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/properties': typeof AdminPropertiesRoute
  '/admin/sellers': typeof AdminSellersRoute
  '/admin/substitutions': typeof AdminSubstitutionsRoute
  '/agent/broker-relationship': typeof AgentBrokerRelationshipRoute
  '/agent/dashboard': typeof AgentDashboardRoute
  '/agent/login': typeof AgentLoginRoute
  '/agent/register': typeof AgentRegisterRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/broker/dashboard': typeof BrokerDashboardRoute
  '/broker/login': typeof BrokerLoginRoute
  '/broker/register': typeof BrokerRegisterRoute
  '/buyer/adverse-action': typeof BuyerAdverseActionRoute
  '/buyer/dashboard': typeof BuyerDashboardRoute
  '/buyer/documents': typeof BuyerDocumentsRoute
  '/buyer/golden-ticket': typeof BuyerGoldenTicketRoute
  '/buyer/login': typeof BuyerLoginRoute
  '/buyer/register': typeof BuyerRegisterRoute
  '/buyer/verification': typeof BuyerVerificationRoute
  '/buyer/wishlist': typeof BuyerWishlistRoute
  '/data-room/$id': typeof DataRoomIdRoute
  '/listings/$id': typeof ListingsIdRoute
  '/listings/new': typeof ListingsNewRoute
  '/onboarding/agreement': typeof OnboardingAgreementRoute
  '/onboarding/fee': typeof OnboardingFeeRoute
  '/onboarding/identity': typeof OnboardingIdentityRoute
  '/onboarding/listing': typeof OnboardingListingRoute
  '/onboarding/media': typeof OnboardingMediaRoute
  '/onboarding/property': typeof OnboardingPropertyRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/r/$token': typeof RTokenRoute
  '/reserve/$id': typeof ReserveIdRoute
  '/reset-password/confirm': typeof ResetPasswordConfirmRoute
  '/admin/': typeof AdminIndexRoute
  '/agent/': typeof AgentIndexRoute
  '/broker/': typeof BrokerIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/agent/onboarding/broker': typeof AgentOnboardingBrokerRoute
  '/agent/onboarding/compliance': typeof AgentOnboardingComplianceRoute
  '/agent/onboarding/insurance': typeof AgentOnboardingInsuranceRoute
  '/agent/onboarding/license-check': typeof AgentOnboardingLicenseCheckRoute
  '/agent/onboarding/license-details': typeof AgentOnboardingLicenseDetailsRoute
  '/api/public/arello-retry': typeof ApiPublicArelloRetryRoute
  '/api/public/broker-relationship-sweep': typeof ApiPublicBrokerRelationshipSweepRoute
  '/api/public/enrollment-maintenance': typeof ApiPublicEnrollmentMaintenanceRoute
  '/api/public/nar-cert-sweep': typeof ApiPublicNarCertSweepRoute
  '/broker/onboarding/banking': typeof BrokerOnboardingBankingRoute
  '/broker/onboarding/compliance': typeof BrokerOnboardingComplianceRoute
  '/broker/onboarding/insurance': typeof BrokerOnboardingInsuranceRoute
  '/broker/onboarding/license-check': typeof BrokerOnboardingLicenseCheckRoute
  '/buyer/onboarding/identity': typeof BuyerOnboardingIdentityRoute
  '/buyer/onboarding/lifestyle': typeof BuyerOnboardingLifestyleRoute
  '/buyer/onboarding/liquidity': typeof BuyerOnboardingLiquidityRoute
  '/buyer/onboarding/payment': typeof BuyerOnboardingPaymentRoute
  '/buyer/onboarding/vetting': typeof BuyerOnboardingVettingRoute
  '/buyer/onboarding/': typeof BuyerOnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/agent'
    | '/broker'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/register'
    | '/reset-password'
    | '/admin/audit-log'
    | '/admin/brokers'
    | '/admin/buyers'
    | '/admin/contacts'
    | '/admin/login'
    | '/admin/payments'
    | '/admin/properties'
    | '/admin/sellers'
    | '/admin/substitutions'
    | '/agent/broker-relationship'
    | '/agent/dashboard'
    | '/agent/login'
    | '/agent/register'
    | '/auth/callback'
    | '/broker/dashboard'
    | '/broker/login'
    | '/broker/register'
    | '/buyer/adverse-action'
    | '/buyer/dashboard'
    | '/buyer/documents'
    | '/buyer/golden-ticket'
    | '/buyer/login'
    | '/buyer/register'
    | '/buyer/verification'
    | '/buyer/wishlist'
    | '/data-room/$id'
    | '/listings/$id'
    | '/listings/new'
    | '/onboarding/agreement'
    | '/onboarding/fee'
    | '/onboarding/identity'
    | '/onboarding/listing'
    | '/onboarding/media'
    | '/onboarding/property'
    | '/properties/$id'
    | '/r/$token'
    | '/reserve/$id'
    | '/reset-password/confirm'
    | '/admin/'
    | '/agent/'
    | '/broker/'
    | '/onboarding/'
    | '/properties/'
    | '/reset-password/'
    | '/agent/onboarding/broker'
    | '/agent/onboarding/compliance'
    | '/agent/onboarding/insurance'
    | '/agent/onboarding/license-check'
    | '/agent/onboarding/license-details'
    | '/api/public/arello-retry'
    | '/api/public/broker-relationship-sweep'
    | '/api/public/enrollment-maintenance'
    | '/api/public/nar-cert-sweep'
    | '/broker/onboarding/banking'
    | '/broker/onboarding/compliance'
    | '/broker/onboarding/insurance'
    | '/broker/onboarding/license-check'
    | '/buyer/onboarding/identity'
    | '/buyer/onboarding/lifestyle'
    | '/buyer/onboarding/liquidity'
    | '/buyer/onboarding/payment'
    | '/buyer/onboarding/vetting'
    | '/buyer/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/register'
    | '/admin/audit-log'
    | '/admin/brokers'
    | '/admin/buyers'
    | '/admin/contacts'
    | '/admin/login'
    | '/admin/payments'
    | '/admin/properties'
    | '/admin/sellers'
    | '/admin/substitutions'
    | '/agent/broker-relationship'
    | '/agent/dashboard'
    | '/agent/login'
    | '/agent/register'
    | '/auth/callback'
    | '/broker/dashboard'
    | '/broker/login'
    | '/broker/register'
    | '/buyer/adverse-action'
    | '/buyer/dashboard'
    | '/buyer/documents'
    | '/buyer/golden-ticket'
    | '/buyer/login'
    | '/buyer/register'
    | '/buyer/verification'
    | '/buyer/wishlist'
    | '/data-room/$id'
    | '/listings/$id'
    | '/listings/new'
    | '/onboarding/agreement'
    | '/onboarding/fee'
    | '/onboarding/identity'
    | '/onboarding/listing'
    | '/onboarding/media'
    | '/onboarding/property'
    | '/properties/$id'
    | '/r/$token'
    | '/reserve/$id'
    | '/reset-password/confirm'
    | '/admin'
    | '/agent'
    | '/broker'
    | '/onboarding'
    | '/properties'
    | '/reset-password'
    | '/agent/onboarding/broker'
    | '/agent/onboarding/compliance'
    | '/agent/onboarding/insurance'
    | '/agent/onboarding/license-check'
    | '/agent/onboarding/license-details'
    | '/api/public/arello-retry'
    | '/api/public/broker-relationship-sweep'
    | '/api/public/enrollment-maintenance'
    | '/api/public/nar-cert-sweep'
    | '/broker/onboarding/banking'
    | '/broker/onboarding/compliance'
    | '/broker/onboarding/insurance'
    | '/broker/onboarding/license-check'
    | '/buyer/onboarding/identity'
    | '/buyer/onboarding/lifestyle'
    | '/buyer/onboarding/liquidity'
    | '/buyer/onboarding/payment'
    | '/buyer/onboarding/vetting'
    | '/buyer/onboarding'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/agent'
    | '/broker'
    | '/contact'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/notifications'
    | '/register'
    | '/reset-password'
    | '/admin/audit-log'
    | '/admin/brokers'
    | '/admin/buyers'
    | '/admin/contacts'
    | '/admin/login'
    | '/admin/payments'
    | '/admin/properties'
    | '/admin/sellers'
    | '/admin/substitutions'
    | '/agent/broker-relationship'
    | '/agent/dashboard'
    | '/agent/login'
    | '/agent/register'
    | '/auth/callback'
    | '/broker/dashboard'
    | '/broker/login'
    | '/broker/register'
    | '/buyer/adverse-action'
    | '/buyer/dashboard'
    | '/buyer/documents'
    | '/buyer/golden-ticket'
    | '/buyer/login'
    | '/buyer/register'
    | '/buyer/verification'
    | '/buyer/wishlist'
    | '/data-room/$id'
    | '/listings/$id'
    | '/listings/new'
    | '/onboarding/agreement'
    | '/onboarding/fee'
    | '/onboarding/identity'
    | '/onboarding/listing'
    | '/onboarding/media'
    | '/onboarding/property'
    | '/properties/$id'
    | '/r/$token'
    | '/reserve/$id'
    | '/reset-password/confirm'
    | '/admin/'
    | '/agent/'
    | '/broker/'
    | '/onboarding/'
    | '/properties/'
    | '/reset-password/'
    | '/agent/onboarding/broker'
    | '/agent/onboarding/compliance'
    | '/agent/onboarding/insurance'
    | '/agent/onboarding/license-check'
    | '/agent/onboarding/license-details'
    | '/api/public/arello-retry'
    | '/api/public/broker-relationship-sweep'
    | '/api/public/enrollment-maintenance'
    | '/api/public/nar-cert-sweep'
    | '/broker/onboarding/banking'
    | '/broker/onboarding/compliance'
    | '/broker/onboarding/insurance'
    | '/broker/onboarding/license-check'
    | '/buyer/onboarding/identity'
    | '/buyer/onboarding/lifestyle'
    | '/buyer/onboarding/liquidity'
    | '/buyer/onboarding/payment'
    | '/buyer/onboarding/vetting'
    | '/buyer/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgentRoute: typeof AgentRouteWithChildren
  BrokerRoute: typeof BrokerRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  BuyerAdverseActionRoute: typeof BuyerAdverseActionRoute
  BuyerDashboardRoute: typeof BuyerDashboardRoute
  BuyerDocumentsRoute: typeof BuyerDocumentsRoute
  BuyerGoldenTicketRoute: typeof BuyerGoldenTicketRoute
  BuyerLoginRoute: typeof BuyerLoginRoute
  BuyerRegisterRoute: typeof BuyerRegisterRoute
  BuyerVerificationRoute: typeof BuyerVerificationRoute
  BuyerWishlistRoute: typeof BuyerWishlistRoute
  DataRoomIdRoute: typeof DataRoomIdRoute
  ListingsIdRoute: typeof ListingsIdRoute
  ListingsNewRoute: typeof ListingsNewRoute
  OnboardingAgreementRoute: typeof OnboardingAgreementRoute
  OnboardingFeeRoute: typeof OnboardingFeeRoute
  OnboardingIdentityRoute: typeof OnboardingIdentityRoute
  OnboardingListingRoute: typeof OnboardingListingRoute
  OnboardingMediaRoute: typeof OnboardingMediaRoute
  OnboardingPropertyRoute: typeof OnboardingPropertyRoute
  PropertiesIdRoute: typeof PropertiesIdRoute
  RTokenRoute: typeof RTokenRoute
  ReserveIdRoute: typeof ReserveIdRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
  ApiPublicArelloRetryRoute: typeof ApiPublicArelloRetryRoute
  ApiPublicBrokerRelationshipSweepRoute: typeof ApiPublicBrokerRelationshipSweepRoute
  ApiPublicEnrollmentMaintenanceRoute: typeof ApiPublicEnrollmentMaintenanceRoute
  ApiPublicNarCertSweepRoute: typeof ApiPublicNarCertSweepRoute
  BuyerOnboardingIdentityRoute: typeof BuyerOnboardingIdentityRoute
  BuyerOnboardingLifestyleRoute: typeof BuyerOnboardingLifestyleRoute
  BuyerOnboardingLiquidityRoute: typeof BuyerOnboardingLiquidityRoute
  BuyerOnboardingPaymentRoute: typeof BuyerOnboardingPaymentRoute
  BuyerOnboardingVettingRoute: typeof BuyerOnboardingVettingRoute
  BuyerOnboardingIndexRoute: typeof BuyerOnboardingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broker': {
      id: '/broker'
      path: '/broker'
      fullPath: '/broker'
      preLoaderRoute: typeof BrokerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/': {
      id: '/reset-password/'
      path: '/'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof ResetPasswordIndexRouteImport
      parentRoute: typeof ResetPasswordRoute
    }
    '/properties/': {
      id: '/properties/'
      path: '/properties'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broker/': {
      id: '/broker/'
      path: '/'
      fullPath: '/broker/'
      preLoaderRoute: typeof BrokerIndexRouteImport
      parentRoute: typeof BrokerRoute
    }
    '/agent/': {
      id: '/agent/'
      path: '/'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof AgentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/reset-password/confirm': {
      id: '/reset-password/confirm'
      path: '/confirm'
      fullPath: '/reset-password/confirm'
      preLoaderRoute: typeof ResetPasswordConfirmRouteImport
      parentRoute: typeof ResetPasswordRoute
    }
    '/reserve/$id': {
      id: '/reserve/$id'
      path: '/reserve/$id'
      fullPath: '/reserve/$id'
      preLoaderRoute: typeof ReserveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/properties/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/property': {
      id: '/onboarding/property'
      path: '/onboarding/property'
      fullPath: '/onboarding/property'
      preLoaderRoute: typeof OnboardingPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/media': {
      id: '/onboarding/media'
      path: '/onboarding/media'
      fullPath: '/onboarding/media'
      preLoaderRoute: typeof OnboardingMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/listing': {
      id: '/onboarding/listing'
      path: '/onboarding/listing'
      fullPath: '/onboarding/listing'
      preLoaderRoute: typeof OnboardingListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/identity': {
      id: '/onboarding/identity'
      path: '/onboarding/identity'
      fullPath: '/onboarding/identity'
      preLoaderRoute: typeof OnboardingIdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/fee': {
      id: '/onboarding/fee'
      path: '/onboarding/fee'
      fullPath: '/onboarding/fee'
      preLoaderRoute: typeof OnboardingFeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/agreement': {
      id: '/onboarding/agreement'
      path: '/onboarding/agreement'
      fullPath: '/onboarding/agreement'
      preLoaderRoute: typeof OnboardingAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/new': {
      id: '/listings/new'
      path: '/listings/new'
      fullPath: '/listings/new'
      preLoaderRoute: typeof ListingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-room/$id': {
      id: '/data-room/$id'
      path: '/data-room/$id'
      fullPath: '/data-room/$id'
      preLoaderRoute: typeof DataRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/wishlist': {
      id: '/buyer/wishlist'
      path: '/buyer/wishlist'
      fullPath: '/buyer/wishlist'
      preLoaderRoute: typeof BuyerWishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/verification': {
      id: '/buyer/verification'
      path: '/buyer/verification'
      fullPath: '/buyer/verification'
      preLoaderRoute: typeof BuyerVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/register': {
      id: '/buyer/register'
      path: '/buyer/register'
      fullPath: '/buyer/register'
      preLoaderRoute: typeof BuyerRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/login': {
      id: '/buyer/login'
      path: '/buyer/login'
      fullPath: '/buyer/login'
      preLoaderRoute: typeof BuyerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/golden-ticket': {
      id: '/buyer/golden-ticket'
      path: '/buyer/golden-ticket'
      fullPath: '/buyer/golden-ticket'
      preLoaderRoute: typeof BuyerGoldenTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/documents': {
      id: '/buyer/documents'
      path: '/buyer/documents'
      fullPath: '/buyer/documents'
      preLoaderRoute: typeof BuyerDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/dashboard': {
      id: '/buyer/dashboard'
      path: '/buyer/dashboard'
      fullPath: '/buyer/dashboard'
      preLoaderRoute: typeof BuyerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/adverse-action': {
      id: '/buyer/adverse-action'
      path: '/buyer/adverse-action'
      fullPath: '/buyer/adverse-action'
      preLoaderRoute: typeof BuyerAdverseActionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broker/register': {
      id: '/broker/register'
      path: '/register'
      fullPath: '/broker/register'
      preLoaderRoute: typeof BrokerRegisterRouteImport
      parentRoute: typeof BrokerRoute
    }
    '/broker/login': {
      id: '/broker/login'
      path: '/login'
      fullPath: '/broker/login'
      preLoaderRoute: typeof BrokerLoginRouteImport
      parentRoute: typeof BrokerRoute
    }
    '/broker/dashboard': {
      id: '/broker/dashboard'
      path: '/dashboard'
      fullPath: '/broker/dashboard'
      preLoaderRoute: typeof BrokerDashboardRouteImport
      parentRoute: typeof BrokerRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/register': {
      id: '/agent/register'
      path: '/register'
      fullPath: '/agent/register'
      preLoaderRoute: typeof AgentRegisterRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/login': {
      id: '/agent/login'
      path: '/login'
      fullPath: '/agent/login'
      preLoaderRoute: typeof AgentLoginRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/dashboard': {
      id: '/agent/dashboard'
      path: '/dashboard'
      fullPath: '/agent/dashboard'
      preLoaderRoute: typeof AgentDashboardRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/broker-relationship': {
      id: '/agent/broker-relationship'
      path: '/broker-relationship'
      fullPath: '/agent/broker-relationship'
      preLoaderRoute: typeof AgentBrokerRelationshipRouteImport
      parentRoute: typeof AgentRoute
    }
    '/admin/substitutions': {
      id: '/admin/substitutions'
      path: '/substitutions'
      fullPath: '/admin/substitutions'
      preLoaderRoute: typeof AdminSubstitutionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sellers': {
      id: '/admin/sellers'
      path: '/sellers'
      fullPath: '/admin/sellers'
      preLoaderRoute: typeof AdminSellersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/properties': {
      id: '/admin/properties'
      path: '/properties'
      fullPath: '/admin/properties'
      preLoaderRoute: typeof AdminPropertiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/buyers': {
      id: '/admin/buyers'
      path: '/buyers'
      fullPath: '/admin/buyers'
      preLoaderRoute: typeof AdminBuyersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/brokers': {
      id: '/admin/brokers'
      path: '/brokers'
      fullPath: '/admin/brokers'
      preLoaderRoute: typeof AdminBrokersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/buyer/onboarding/': {
      id: '/buyer/onboarding/'
      path: '/buyer/onboarding'
      fullPath: '/buyer/onboarding/'
      preLoaderRoute: typeof BuyerOnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/onboarding/vetting': {
      id: '/buyer/onboarding/vetting'
      path: '/buyer/onboarding/vetting'
      fullPath: '/buyer/onboarding/vetting'
      preLoaderRoute: typeof BuyerOnboardingVettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/onboarding/payment': {
      id: '/buyer/onboarding/payment'
      path: '/buyer/onboarding/payment'
      fullPath: '/buyer/onboarding/payment'
      preLoaderRoute: typeof BuyerOnboardingPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/onboarding/liquidity': {
      id: '/buyer/onboarding/liquidity'
      path: '/buyer/onboarding/liquidity'
      fullPath: '/buyer/onboarding/liquidity'
      preLoaderRoute: typeof BuyerOnboardingLiquidityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/onboarding/lifestyle': {
      id: '/buyer/onboarding/lifestyle'
      path: '/buyer/onboarding/lifestyle'
      fullPath: '/buyer/onboarding/lifestyle'
      preLoaderRoute: typeof BuyerOnboardingLifestyleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer/onboarding/identity': {
      id: '/buyer/onboarding/identity'
      path: '/buyer/onboarding/identity'
      fullPath: '/buyer/onboarding/identity'
      preLoaderRoute: typeof BuyerOnboardingIdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broker/onboarding/license-check': {
      id: '/broker/onboarding/license-check'
      path: '/onboarding/license-check'
      fullPath: '/broker/onboarding/license-check'
      preLoaderRoute: typeof BrokerOnboardingLicenseCheckRouteImport
      parentRoute: typeof BrokerRoute
    }
    '/broker/onboarding/insurance': {
      id: '/broker/onboarding/insurance'
      path: '/onboarding/insurance'
      fullPath: '/broker/onboarding/insurance'
      preLoaderRoute: typeof BrokerOnboardingInsuranceRouteImport
      parentRoute: typeof BrokerRoute
    }
    '/broker/onboarding/compliance': {
      id: '/broker/onboarding/compliance'
      path: '/onboarding/compliance'
      fullPath: '/broker/onboarding/compliance'
      preLoaderRoute: typeof BrokerOnboardingComplianceRouteImport
      parentRoute: typeof BrokerRoute
    }
    '/broker/onboarding/banking': {
      id: '/broker/onboarding/banking'
      path: '/onboarding/banking'
      fullPath: '/broker/onboarding/banking'
      preLoaderRoute: typeof BrokerOnboardingBankingRouteImport
      parentRoute: typeof BrokerRoute
    }
    '/api/public/nar-cert-sweep': {
      id: '/api/public/nar-cert-sweep'
      path: '/api/public/nar-cert-sweep'
      fullPath: '/api/public/nar-cert-sweep'
      preLoaderRoute: typeof ApiPublicNarCertSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/enrollment-maintenance': {
      id: '/api/public/enrollment-maintenance'
      path: '/api/public/enrollment-maintenance'
      fullPath: '/api/public/enrollment-maintenance'
      preLoaderRoute: typeof ApiPublicEnrollmentMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/broker-relationship-sweep': {
      id: '/api/public/broker-relationship-sweep'
      path: '/api/public/broker-relationship-sweep'
      fullPath: '/api/public/broker-relationship-sweep'
      preLoaderRoute: typeof ApiPublicBrokerRelationshipSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/arello-retry': {
      id: '/api/public/arello-retry'
      path: '/api/public/arello-retry'
      fullPath: '/api/public/arello-retry'
      preLoaderRoute: typeof ApiPublicArelloRetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/onboarding/license-details': {
      id: '/agent/onboarding/license-details'
      path: '/onboarding/license-details'
      fullPath: '/agent/onboarding/license-details'
      preLoaderRoute: typeof AgentOnboardingLicenseDetailsRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/onboarding/license-check': {
      id: '/agent/onboarding/license-check'
      path: '/onboarding/license-check'
      fullPath: '/agent/onboarding/license-check'
      preLoaderRoute: typeof AgentOnboardingLicenseCheckRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/onboarding/insurance': {
      id: '/agent/onboarding/insurance'
      path: '/onboarding/insurance'
      fullPath: '/agent/onboarding/insurance'
      preLoaderRoute: typeof AgentOnboardingInsuranceRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/onboarding/compliance': {
      id: '/agent/onboarding/compliance'
      path: '/onboarding/compliance'
      fullPath: '/agent/onboarding/compliance'
      preLoaderRoute: typeof AgentOnboardingComplianceRouteImport
      parentRoute: typeof AgentRoute
    }
    '/agent/onboarding/broker': {
      id: '/agent/onboarding/broker'
      path: '/onboarding/broker'
      fullPath: '/agent/onboarding/broker'
      preLoaderRoute: typeof AgentOnboardingBrokerRouteImport
      parentRoute: typeof AgentRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminBrokersRoute: typeof AdminBrokersRoute
  AdminBuyersRoute: typeof AdminBuyersRoute
  AdminContactsRoute: typeof AdminContactsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPropertiesRoute: typeof AdminPropertiesRoute
  AdminSellersRoute: typeof AdminSellersRoute
  AdminSubstitutionsRoute: typeof AdminSubstitutionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminBrokersRoute: AdminBrokersRoute,
  AdminBuyersRoute: AdminBuyersRoute,
  AdminContactsRoute: AdminContactsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPropertiesRoute: AdminPropertiesRoute,
  AdminSellersRoute: AdminSellersRoute,
  AdminSubstitutionsRoute: AdminSubstitutionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AgentRouteChildren {
  AgentBrokerRelationshipRoute: typeof AgentBrokerRelationshipRoute
  AgentDashboardRoute: typeof AgentDashboardRoute
  AgentLoginRoute: typeof AgentLoginRoute
  AgentRegisterRoute: typeof AgentRegisterRoute
  AgentIndexRoute: typeof AgentIndexRoute
  AgentOnboardingBrokerRoute: typeof AgentOnboardingBrokerRoute
  AgentOnboardingComplianceRoute: typeof AgentOnboardingComplianceRoute
  AgentOnboardingInsuranceRoute: typeof AgentOnboardingInsuranceRoute
  AgentOnboardingLicenseCheckRoute: typeof AgentOnboardingLicenseCheckRoute
  AgentOnboardingLicenseDetailsRoute: typeof AgentOnboardingLicenseDetailsRoute
}

const AgentRouteChildren: AgentRouteChildren = {
  AgentBrokerRelationshipRoute: AgentBrokerRelationshipRoute,
  AgentDashboardRoute: AgentDashboardRoute,
  AgentLoginRoute: AgentLoginRoute,
  AgentRegisterRoute: AgentRegisterRoute,
  AgentIndexRoute: AgentIndexRoute,
  AgentOnboardingBrokerRoute: AgentOnboardingBrokerRoute,
  AgentOnboardingComplianceRoute: AgentOnboardingComplianceRoute,
  AgentOnboardingInsuranceRoute: AgentOnboardingInsuranceRoute,
  AgentOnboardingLicenseCheckRoute: AgentOnboardingLicenseCheckRoute,
  AgentOnboardingLicenseDetailsRoute: AgentOnboardingLicenseDetailsRoute,
}

const AgentRouteWithChildren = AgentRoute._addFileChildren(AgentRouteChildren)

interface BrokerRouteChildren {
  BrokerDashboardRoute: typeof BrokerDashboardRoute
  BrokerLoginRoute: typeof BrokerLoginRoute
  BrokerRegisterRoute: typeof BrokerRegisterRoute
  BrokerIndexRoute: typeof BrokerIndexRoute
  BrokerOnboardingBankingRoute: typeof BrokerOnboardingBankingRoute
  BrokerOnboardingComplianceRoute: typeof BrokerOnboardingComplianceRoute
  BrokerOnboardingInsuranceRoute: typeof BrokerOnboardingInsuranceRoute
  BrokerOnboardingLicenseCheckRoute: typeof BrokerOnboardingLicenseCheckRoute
}

const BrokerRouteChildren: BrokerRouteChildren = {
  BrokerDashboardRoute: BrokerDashboardRoute,
  BrokerLoginRoute: BrokerLoginRoute,
  BrokerRegisterRoute: BrokerRegisterRoute,
  BrokerIndexRoute: BrokerIndexRoute,
  BrokerOnboardingBankingRoute: BrokerOnboardingBankingRoute,
  BrokerOnboardingComplianceRoute: BrokerOnboardingComplianceRoute,
  BrokerOnboardingInsuranceRoute: BrokerOnboardingInsuranceRoute,
  BrokerOnboardingLicenseCheckRoute: BrokerOnboardingLicenseCheckRoute,
}

const BrokerRouteWithChildren =
  BrokerRoute._addFileChildren(BrokerRouteChildren)

interface ResetPasswordRouteChildren {
  ResetPasswordConfirmRoute: typeof ResetPasswordConfirmRoute
  ResetPasswordIndexRoute: typeof ResetPasswordIndexRoute
}

const ResetPasswordRouteChildren: ResetPasswordRouteChildren = {
  ResetPasswordConfirmRoute: ResetPasswordConfirmRoute,
  ResetPasswordIndexRoute: ResetPasswordIndexRoute,
}

const ResetPasswordRouteWithChildren = ResetPasswordRoute._addFileChildren(
  ResetPasswordRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AgentRoute: AgentRouteWithChildren,
  BrokerRoute: BrokerRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  BuyerAdverseActionRoute: BuyerAdverseActionRoute,
  BuyerDashboardRoute: BuyerDashboardRoute,
  BuyerDocumentsRoute: BuyerDocumentsRoute,
  BuyerGoldenTicketRoute: BuyerGoldenTicketRoute,
  BuyerLoginRoute: BuyerLoginRoute,
  BuyerRegisterRoute: BuyerRegisterRoute,
  BuyerVerificationRoute: BuyerVerificationRoute,
  BuyerWishlistRoute: BuyerWishlistRoute,
  DataRoomIdRoute: DataRoomIdRoute,
  ListingsIdRoute: ListingsIdRoute,
  ListingsNewRoute: ListingsNewRoute,
  OnboardingAgreementRoute: OnboardingAgreementRoute,
  OnboardingFeeRoute: OnboardingFeeRoute,
  OnboardingIdentityRoute: OnboardingIdentityRoute,
  OnboardingListingRoute: OnboardingListingRoute,
  OnboardingMediaRoute: OnboardingMediaRoute,
  OnboardingPropertyRoute: OnboardingPropertyRoute,
  PropertiesIdRoute: PropertiesIdRoute,
  RTokenRoute: RTokenRoute,
  ReserveIdRoute: ReserveIdRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
  ApiPublicArelloRetryRoute: ApiPublicArelloRetryRoute,
  ApiPublicBrokerRelationshipSweepRoute: ApiPublicBrokerRelationshipSweepRoute,
  ApiPublicEnrollmentMaintenanceRoute: ApiPublicEnrollmentMaintenanceRoute,
  ApiPublicNarCertSweepRoute: ApiPublicNarCertSweepRoute,
  BuyerOnboardingIdentityRoute: BuyerOnboardingIdentityRoute,
  BuyerOnboardingLifestyleRoute: BuyerOnboardingLifestyleRoute,
  BuyerOnboardingLiquidityRoute: BuyerOnboardingLiquidityRoute,
  BuyerOnboardingPaymentRoute: BuyerOnboardingPaymentRoute,
  BuyerOnboardingVettingRoute: BuyerOnboardingVettingRoute,
  BuyerOnboardingIndexRoute: BuyerOnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
