/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as OnboardingPropertyRouteImport } from './routes/onboarding.property'
import { Route as OnboardingMediaRouteImport } from './routes/onboarding.media'
import { Route as OnboardingListingRouteImport } from './routes/onboarding.listing'
import { Route as OnboardingIdentityRouteImport } from './routes/onboarding.identity'
import { Route as OnboardingAgreementRouteImport } from './routes/onboarding.agreement'
import { Route as ListingsNewRouteImport } from './routes/listings.new'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingPropertyRoute = OnboardingPropertyRouteImport.update({
  id: '/onboarding/property',
  path: '/onboarding/property',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingMediaRoute = OnboardingMediaRouteImport.update({
  id: '/onboarding/media',
  path: '/onboarding/media',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingListingRoute = OnboardingListingRouteImport.update({
  id: '/onboarding/listing',
  path: '/onboarding/listing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIdentityRoute = OnboardingIdentityRouteImport.update({
  id: '/onboarding/identity',
  path: '/onboarding/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingAgreementRoute = OnboardingAgreementRouteImport.update({
  id: '/onboarding/agreement',
  path: '/onboarding/agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsNewRoute = ListingsNewRouteImport.update({
  id: '/listings/new',
  path: '/listings/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/listings/$id': typeof ListingsIdRoute
  '/listings/new': typeof ListingsNewRoute
  '/onboarding/agreement': typeof OnboardingAgreementRoute
  '/onboarding/identity': typeof OnboardingIdentityRoute
  '/onboarding/listing': typeof OnboardingListingRoute
  '/onboarding/media': typeof OnboardingMediaRoute
  '/onboarding/property': typeof OnboardingPropertyRoute
  '/onboarding/': typeof OnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/listings/$id': typeof ListingsIdRoute
  '/listings/new': typeof ListingsNewRoute
  '/onboarding/agreement': typeof OnboardingAgreementRoute
  '/onboarding/identity': typeof OnboardingIdentityRoute
  '/onboarding/listing': typeof OnboardingListingRoute
  '/onboarding/media': typeof OnboardingMediaRoute
  '/onboarding/property': typeof OnboardingPropertyRoute
  '/onboarding': typeof OnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/listings/$id': typeof ListingsIdRoute
  '/listings/new': typeof ListingsNewRoute
  '/onboarding/agreement': typeof OnboardingAgreementRoute
  '/onboarding/identity': typeof OnboardingIdentityRoute
  '/onboarding/listing': typeof OnboardingListingRoute
  '/onboarding/media': typeof OnboardingMediaRoute
  '/onboarding/property': typeof OnboardingPropertyRoute
  '/onboarding/': typeof OnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/auth/callback'
    | '/listings/$id'
    | '/listings/new'
    | '/onboarding/agreement'
    | '/onboarding/identity'
    | '/onboarding/listing'
    | '/onboarding/media'
    | '/onboarding/property'
    | '/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/auth/callback'
    | '/listings/$id'
    | '/listings/new'
    | '/onboarding/agreement'
    | '/onboarding/identity'
    | '/onboarding/listing'
    | '/onboarding/media'
    | '/onboarding/property'
    | '/onboarding'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/auth/callback'
    | '/listings/$id'
    | '/listings/new'
    | '/onboarding/agreement'
    | '/onboarding/identity'
    | '/onboarding/listing'
    | '/onboarding/media'
    | '/onboarding/property'
    | '/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ListingsIdRoute: typeof ListingsIdRoute
  ListingsNewRoute: typeof ListingsNewRoute
  OnboardingAgreementRoute: typeof OnboardingAgreementRoute
  OnboardingIdentityRoute: typeof OnboardingIdentityRoute
  OnboardingListingRoute: typeof OnboardingListingRoute
  OnboardingMediaRoute: typeof OnboardingMediaRoute
  OnboardingPropertyRoute: typeof OnboardingPropertyRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/property': {
      id: '/onboarding/property'
      path: '/onboarding/property'
      fullPath: '/onboarding/property'
      preLoaderRoute: typeof OnboardingPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/media': {
      id: '/onboarding/media'
      path: '/onboarding/media'
      fullPath: '/onboarding/media'
      preLoaderRoute: typeof OnboardingMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/listing': {
      id: '/onboarding/listing'
      path: '/onboarding/listing'
      fullPath: '/onboarding/listing'
      preLoaderRoute: typeof OnboardingListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/identity': {
      id: '/onboarding/identity'
      path: '/onboarding/identity'
      fullPath: '/onboarding/identity'
      preLoaderRoute: typeof OnboardingIdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/agreement': {
      id: '/onboarding/agreement'
      path: '/onboarding/agreement'
      fullPath: '/onboarding/agreement'
      preLoaderRoute: typeof OnboardingAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/new': {
      id: '/listings/new'
      path: '/listings/new'
      fullPath: '/listings/new'
      preLoaderRoute: typeof ListingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ListingsIdRoute: ListingsIdRoute,
  ListingsNewRoute: ListingsNewRoute,
  OnboardingAgreementRoute: OnboardingAgreementRoute,
  OnboardingIdentityRoute: OnboardingIdentityRoute,
  OnboardingListingRoute: OnboardingListingRoute,
  OnboardingMediaRoute: OnboardingMediaRoute,
  OnboardingPropertyRoute: OnboardingPropertyRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
